SELECT
  tenant_id,
  "name",
  honorific,
  email,
  "order",
  enabled_notification,
  last_sent_at,
  created_at,
  updated_at
FROM public.completion_notification_users
WHERE (tenant_id, email) IN (
  (11, 'hiroshi-ogata@saiseikaikumamoto.jp'),
  (60, 'k-mochizuki@kkr-smc.com'),
  (162, 'yasuhiko_kamogawa@kcho.jp'),
  (89, 's_murakami@jikei.ac.jp'),
  (78, 'sakurai-shin@rakuwa.or.jp'),
  (121, 'shiraishi.kohei@jp.panasonic.com'),
  (143, 'yoshinobu.ya@hp.pref.hyogo.jp'),
  (143, 'Mio_Fujimoto@pref.hyogo.lg.jp'),
  (167, 'y-hase@teikyo-u.ac.jp'),
  (105, 'agata_fumiki@gm.shinshu-u.ac.jp'),
  (70, 'a294097@ych.or.jp'),
  (170, 'ikema.tomishiro.hp@gmail.com'),
  (170, 'chiiki@yuuai.or.jp'),
  (274, 'minagawas@pref.tottori.lg.jp'),
  (274, 'tatebes@tp-ch.jp'),
  (274, 'zenporenkei@tp-ch.jp'),
  (274, 'ookuboy@pref.tottori.lg.jp'),
  (171, 'nozawa.19008@kanagawa-pho.jp'),
  (271, 'imaseki.hsc@chubuh.johas.go.jp'),
  (271, 'renkei@chubuh.johas.go.jp'),
  (13, 'kurama.yanagidate@jmagrp.or.jp'),
  (165, 'munekiyo-masaaki@rakuwa.or.jp'),
  (165, 'kurata-akito@rakuwa.or.jp'),
  (237, 'hayashimi@ekisai.or.jp'),
  (237, 'kainumaa@ekisai.or.jp'),
  (237, 'kondouda@ekisai.or.jp'),
  (273, 'itiiki@jimu.hokudai.ac.jp'),
  (33, 'a_kinjou@ns.omotokai.jp'),
  (24, 'douai-chiikirenkei@outlook.jp'),
  (137, 'h.ueno@marianna-u.ac.jp'),
  (23, 'toyofuku.r@jihs.go.jp'),
  (137, 'shota.takizawa@marianna-u.ac.jp'),
  (137, 'naoki.kunishige@marianna-u.ac.jp'),
  (482, 'hashimoto.tsutomu.tk@mail.hosp.go.jp'),
  (137, 'r2aizawa@marianna-u.ac.jp'),
  (167, 'm-renkei@teikyo-u.ac.jp'),
  (137, 'tomofumi.hoshina@marianna-u.ac.jp'),
  (517, 'okabe@marianna-u.ac.jp'),
  (121, 'funai.kazuyuki@jp.panasonic.com'),
  (517, 'awave@marianna-u.ac.jp'),
  (121, 'watanabe.takumi001@jp.panasonic.com'),
  (517, 'satomi.tsuchiya@marianna-u.ac.jp'),
  (482, 'uekama.takuto.yq@mail.hosp.go.jp'),
  (157, 'renkei@okayamasaiseikai.or.jp'),
  (482, 'motomura.koki.wj@mail.hosp.go.jp'),
  (482, 'kai.saori.su@mail.hosp.go.jp'),
  (482, 'seki.yukiko.ew@mail.hosp.go.jp'),
  (516, 'tsuyoshi_sawada@tmhp.jp'),
  (516, 'natsumi_shigeta@tmhp.jp'),
  (518, 'kinoshita.akira@nihon-u.ac.jp'),
  (518, 'kariwano.youko@nihon-u.ac.jp'),
  (22, 'shoya.shishido@medup.jp'),
  (551, 'ueno-hi@pref.gunma.lg.jp')
)
ORDER BY tenant_id, "order";
